# -*- coding: utf-8 -*-
"""train.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EtfngOP-thJ0IhBfF_I4PsyYaiKj33hq

https://udea.zoom.us/rec/play/0om2bEi9oQQwRBtJbM58KTvbuXQWGOQtNX0OqwTDdw47R4eZmz2E4Egjfbg_rTsLCyfQyGMYL46okMpp.GHPm1wOBgCO9gYIK?canPlayFromShare=true&from=share_recording_detail&continueMode=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fudea.zoom.us%2Frec%2Fshare%2Fj_xeEDbAlREO_Zht4U_N3HG0S7cKvy7WrpxJyxF2-bD6UX3ia8J41xsHGWzPJ-Xh.P-h_Uo3fuVTnvR2n
"""

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
import pickle

# Para obetner el dataset
train_data = pd.read_csv('train_data.csv')

# Cargar los datos de entrenamiento
train_data = pd.read_csv("train_data.csv")

# Dividir los datos en características (X) y etiquetas (y)
X_train = train_data.drop(columns=["Sales"])
y_train = train_data['Sales'].values.reshape(-1, 1)

# Inicializar el modelo
model = RandomForestClassifier()

# Entrenar el modelo
model.fit(X_train, y_train)

# Guardar el modelo entrenado en disco
with open("trained_model.pkl", "wb") as file:
    pickle.dump(model, file)